### ISSUE TITLE
Menu system

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [rogerclarkmelbourne/Radioddity_GD-77#16]
Looking in the ROM data, its almost certainly using a menu system which generates a data table.

It could be a custom menu system developed by TYT or its possibly based on something else.

We probably need to extract the data and post it here, in case any wants to have a go working out its structure.

BTW. There must be icon graphics somewhere which are used in the menu system

**Comment by rogerclarkmelbourne** [comment]
I set a breakpoint on the memory that holds the text for "Contact" and this is roughly the calls stack that caused the read

Note. The stack trace can't be totally relied upon.


```
(gdb) rwatch *0x7323c

Hardware read watchpoint 1: *0x7323c
(gdb) b *0xfa0c
Breakpoint 2 at 0xfa0c
Breakpoint 2, 0x0000fa0c in ?? ()
Breakpoint 2, 0x0000fa0c in ?? ()
Breakpoint 2, 0x0000fa0c in ?? ()
Breakpoint 2, 0x0000fa0c in ?? ()
Breakpoint 2, 0x0000fa0c in ?? ()
Breakpoint 2, 0x0000fa0c in ?? ()
Breakpoint 2, 0x0000fa0c in ?? ()
Breakpoint 2, 0x0000fa0c in ?? ()
Breakpoint 2, 0x0000fa0c in ?? ()
Breakpoint 2, 0x0000fa0c in ?? ()
Breakpoint 2, 0x0000fa0c in ?? ()
Breakpoint 2, 0x0000fa0c in ?? ()
Breakpoint 2, 0x0000fa0c in ?? ()
Breakpoint 2, 0x0000fa0c in ?? ()
Breakpoint 2, 0x0000fa0c in ?? ()
Breakpoint 2, 0x0000fa0c in ?? ()
Breakpoint 2, 0x0000fa0c in ?? ()
Breakpoint 2, 0x0000fa0c in ?? ()
Breakpoint 2, 0x0000fa0c in ?? ()
Breakpoint 2, 0x0000fa0c in ?? ()
Breakpoint 2, 0x0000fa0c in ?? ()
Breakpoint 2, 0x0000fa0c in ?? ()
Breakpoint 2, 0x0000fa0c in ?? ()
Breakpoint 2, 0x0000fa0c in ?? ()
Breakpoint 2, 0x0000fa0c in ?? ()
Breakpoint 2, 0x0000fa0c in ?? ()
Breakpoint 2, 0x0000fa0c in ?? ()
(gdb) bt
#0  0x0000fa0c in ?? ()
#1  0x0003add0 in ?? ()
#2  0x0003add0 in ?? ()

(gdb) b *0x3ada0
Breakpoint 3 at 0x3ada0
Breakpoint 3, 0x0003ada0 in ?? ()
Breakpoint 3, 0x0003ada0 in ?? ()
Breakpoint 3, 0x0003ada0 in ?? ()
Breakpoint 3, 0x0003ada0 in ?? ()
Breakpoint 3, 0x0003ada0 in ?? ()
Breakpoint 3, 0x0003ada0 in ?? ()
Breakpoint 3, 0x0003ada0 in ?? ()
(gdb) bt
#0  0x0003ada0 in ?? ()
#1  0x0003391a in ?? ()
#2  0x0003391a in ?? ()

(gdb) b *0x33916
Breakpoint 4 at 0x33916
Breakpoint 4, 0x00033916 in ?? ()
Breakpoint 4, 0x00033916 in ?? ()
Breakpoint 4, 0x00033916 in ?? ()
Breakpoint 4, 0x00033916 in ?? ()
(gdb) bt
#0  0x00033916 in ?? ()
#1  0x00034584 in ?? ()
#2  0x00034584 in ?? ()

(gdb) b *0x3453e
Breakpoint 5 at 0x3453e
Breakpoint 5, 0x0003453e in ?? ()
Breakpoint 5, 0x0003453e in ?? ()
Breakpoint 5, 0x0003453e in ?? ()
Breakpoint 5, 0x0003453e in ?? ()
Breakpoint 5, 0x0003453e in ?? ()
Breakpoint 5, 0x0003453e in ?? ()
(gdb) bt
#0  0x0003453e in ?? ()
#1  0x00033906 in ?? ()
#2  0x00033906 in ?? ()

(gdb) b *0x338a6
Breakpoint 6 at 0x338a6
Breakpoint 6, 0x000338a6 in ?? ()
(gdb) bt
#0  0x000338a6 in ?? ()
#1  0x000290ec in ?? ()
#2  0x000290ec in ?? ()
```

0x338a6

gets called as soon as the green menu button is pressed.

I think the functions lower in the tree are probably calls to load the individual sub menus (of contacts)
i.e there are 5 sub menus.
I know that these sub functions are sometimes called 6 times, but it could be a while loop until it gets returned a value of 0 for no more sub menus

**Comment by forkoz** [comment]
290ec is in the middle of a function.

**Comment by forkoz** [comment]
That 0x3ada0 sure goes around a lot... it might be good to compare this menu behavior in digital vs analog mode since you get a different menu in each.

**Comment by rogerclarkmelbourne** [comment]
@forkoz 

Re: 0x290ec

Its GDB. For some reason it can't analyse the stack in some cases.
What I often have to do is to use Ghidra to find the parents of a particular function, and then put breakpoints in all the parents, then restart the application, and do the same process again, e.g. push a button and hopefully one of the parents in which I put the breakpoint is the path for the code in this instance.

**Comment by forkoz** [comment]
wow, that's painful. With ida, it controls the debugger be it GDB or the native one.

**Comment by rogerclarkmelbourne** [comment]
I asked the NSA about this via a issue on their repo, and they said a debugger interface was under development but it would be some time before it was finished.

**Comment by rogerclarkmelbourne** [comment]
FYI.

I have not had time to do this yet, but since we've already established that Ghirda does not handle the linkage between the functions an the menu structure....

Its likely that any functions which Ghirda thinks have no usage count, are something to do with the Menu or possibly something to do with the RTOS or some other system with pointer related callbacks.

I noticed that Ghidra has a Symbol Table listing, with columns for Reference Count and "Off cut reference count"

I filtered these via excel, to produce this list of function addresses, which have zero reference and zero off cut reference count


```
00006fb4
00008abc
0000de6c
0000df04
00010b24
00010b40
00010bbc
00011258
0001126a
00011278
00011472
00011494
000114b8
000114dc
000114f6
00011508
00011a94
00011b8a
000120ea
000124fa
00012b00
00013bca
00013e68
00013e7c
000152a2
00015416
0001571c
00015786
00015c6a
00016814
0001683e
000174b2
00018f48
000197e4
00019f8c
00019fbe
0001a02a
0001a0cc
0001a140
0001a2f8
0001a84c
0001b28c
0001e4b4
0001ebc6
0001effc
0001f054
0001fab4
0001fb22
0001fe8c
0001ff1e
0001ff78
00020640
00020778
000207b2
00020874
00020914
0002180a
00021878
000218a2
000218d6
00021930
00021ae8
00021c10
000224c2
0002342a
0002422c
00024c76
00024cd0
00024cea
00024d2a
00024da6
00024e1a
00024e7e
00025036
000250b4
00025156
000251da
0002527c
0002531a
00025390
00025420
000254b0
00025590
00026a12
00026a22
00026eb6
0002763a
000280bc
0002880c
0002927a
00029304
00029464
000295f4
0002be7e
0002ccd4
0002d626
0002eb00
0002edd2
0002f32a
00032c64
00032c76
00032cee
0003357e
000335d2
0003365e
00035bb2
0003674a
00037208
000379ac
0003960a
0003b0de
0003b33c
0003c060
0003c516
0003e91e
00040132
000402e2
00041b52
00047832
00047e7c
000492fe
0004991a
0004b21a
0004f10c
0005364a
000542a0
000542b0
00054728
00054764
00054980
000559e8
00055e92
0005b404
0005b494
0005c2be
00064810
00065396
000656a4
000659b4
0006906a
0006942c
0006963e
00069660
00069688
0006986c
00069c68
0006a026
0006a43c
0006a476
0006a4b4
0006a4ee
0006a52c
```

I tried putting them all into GDB at once, and it didnt give an errors, but it seems to patch the firmware to implement the breakpoints, and the code then doesnt run correctly.

I tried just 32 breakpoints, but it was almost as bad, and the code didnt run correctly.

So I may have to test things in groups of 16, which will take some time

I can rule out any breakpoints that trigger straight away...

But I will have to manually go though the menu's and see which breakpoints are triggered by which menu :-(

Unless we can spot a pattern...

BTW.
I did a scatter plot of the address (in decimal) and it this

![image](https://user-images.githubusercontent.com/6146984/55321494-851be880-54c5-11e9-8e8e-cc83868c51dd.png)

But I don't think it give any useful information

**Comment by rogerclarkmelbourne** [comment]
I found a massive table of pointers, which all link to quite small functions, and a few of these functions are already known to be part of the menu system.

So I am pretty sure all the other pointers in the list are to menu functions, literally hundreds of them.

I have now renamed all the functions pointed to by the menu pointers table, and I will post a list of these functions and their addresses.
Also the memory location just before the list of pointers, is a pointer to the memory location which gets updated depending on which menu you are in, so I think it’s most likely storing the index into the pointer table for the function which is currently handling the menu input.

However, I have not cross checked this hypothesis yet.

I have also not worked out how the function index ties in with the data structure which contains the names of the menu options.

When I looked at how it displayed the version number, the display part of the different menus seems to be the same, so  I think there is an overall menu handler function, which reads the data structure containing the names of each of the options, and which must also contain an index into the function pointers list.
This would explain why some of the menu functions seem to just return, because they are likely to be for when you select a menu, which just has a load of sub menus, and not any direct functionality.

In the long term, it would be good to move the menu data structure into flash memory as it would allow for translations into other languages. 
I presume at the moment perhaps there are 2 complete copies of the whole structure, one of English and one for Chinese, because the text of the strings seems mixed in with too much other data for it to be purely a table of strings.

**Comment by rogerclarkmelbourne** [comment]
The pointer table for the menu functions seems to start here 0x235c0

The 32 bit value just before this, at 0x235bc seems to store the menu number e.g. 0x0E is seems to be the Manual Dial menu number but this doesnt seem to match with the index into the function pointers

There is code to look at offset 0x2d from the memory location that contains the menu number, so this location seems important to the operation of the menus

**Comment by rogerclarkmelbourne** [comment]
FYI. 

`        000235dc 05 91 02 00     addr       Menu_item-level_1_item_selected-00029104+1`

I've now patched the function which gets called when a Zone is selected

```
        00023620 c9 94 02 00     addr       Menu_item_Zone-000294c8+1
        00023624 6f 8c 02 00     addr       Menu_item-00028c6e+1
        00023628 b9 8c 02 00     addr       Menu_item-00028cb8+1
        0002362c 15 55 06 00     addr       Patch_Menu_item_zone_selected_zone-00065514+1
```

As I need to wrap that function, because I need to clear the override on the TG when they select a zone.


But it looks like each menu item has 4 pointers assigned to it.
I'm fairly sure there is one for the Up arrow function, on for Down arrow, one for the Green button and probably one for the red button.
                  
 ```
                            LAB_Menu_up_arrow-000234e2                      XREF[1]:     000234d6(j)  
        000234e2 0f f2 dc 00     adr.w      r0,0x235c0
        000234e6 e1 78           ldrb       r1,[r4,#0x3]=>DAT_Menu_number-1fff55e7           = 9Fh
        000234e8 00 eb 01 10     add.w      r0,r0,r1, lsl #0x4
        000234ec 40 68           ldr        r0,[r0,#0x4]
        000234ee 80 47           blx        r0
        000234f0 11 e0           b          LAB_00023516
                             LAB_Menu_down_arrow-000234f2                    XREF[1]:     000234de(j)  
        000234f2 0f f2 cc 00     adr.w      r0,0x235c0
        000234f6 e1 78           ldrb       r1,[r4,#0x3]=>DAT_Menu_number-1fff55e7           = 9Fh
        000234f8 00 eb 01 10     add.w      r0,r0,r1, lsl #0x4
        000234fc 80 68           ldr        r0,[r0,#0x8]
        000234fe 80 47           blx        r0
        00023500 09 e0           b          LAB_00023516
                             LAB_00023502                                    XREF[1]:     000234e0(j)  
        00023502 b1 f5 90 7f     cmp.w      r1,#0x120
        00023506 06 d0           beq        LAB_00023516
        00023508 0f f2 b4 00     adr.w      r0,0x235c0
        0002350c e1 78           ldrb       r1,[r4,#0x3]=>DAT_Menu_number-1fff55e7           = 9Fh
        0002350e 00 eb 01 10     add.w      r0,r0,r1, lsl #0x4
        00023512 c0 68           ldr        r0,[r0,#0xc]
        00023514 80 47           blx        r0

```

The individual menu item functions may read the menu data table and assign a new menu number depending on what the user selects

BTW. I wonder if the structure of the menus is the same as the MD-380, as AFIK they managed to add new menus

**Comment by forkoz** [comment]
We have a few nullsubs there to take over for new items.
